sudo: false
dist: trusty

language: java

jdk:
- openjdk11

install: true
script: mvn package

after_success: cp target/massim-*.tar.gz massim-${TRAVIS_BRANCH}.tar.gz

deploy:
  provider: releases
  api_key:
    secure: JVCX8vo5I5gTXFM7+cSPlD9NWq9v+NI09hd17glPoHgYLGfA/GQTPzb+x434qXK9wdHv5hI4Wq7DJn3VB4Nvj5B4de8uvz85clZ5luxeSo50CiQSJZZtF+QImwviLub1dDlEYttmWemjhibTVhelXcRWyeGkFmtP/ED5oHyiIv2NP1J6w+PzlT8J1v6wJ74e2id96tjEYlah82MDzo5D10M6kIVEnVbq6FvJG2PBz/2OQtbR6keruuhVHLOocU75rgCULn6yN4qWNNuu+6b4HwBBmM8b/vdZkn3TZYJ7xT2auAfG21kfmxBQgAtcrtl+LynsCycDjdS9P7B1TzwSqIX5q74xrTcdaUYotqWlj+M64CJIpocrord5tCSxUXjkWoNGKNpqYyfksMy5cAy5Z2iFxZZFIRzr5/8x0DJlgnI7GNO+0mN0gutjZdJViz7SEagqpm1HmtvKurch1Q320GTX34p1BlmI4KXzw3SlDPO2So3hIR9sxG4SBR0eTiXJ6cBJD6p4ObkbhYAgMFI/aAHq59bVWdtWkov9lWWpJyN7+/da4fgEoNLEEXNR+Z5r4dNHOv9/8FNKkO4KHKHZ/097iHi8n7OnWH6C5nZrAloMxV0L9c4acXObTQ5J1P9q+TBv2EDRzlYFLls9z+wj8omCeibz1vLRqG+E2gHpsMk=
  file: target/massim-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: agentcontest/massim_2019
    branch: master

addons:
  artifacts:
    bucket: agentcontest
    s3_region: eu-west-1
    paths: $(ls massim-*.tar.gz)
    target_paths: massim
    cache_control: public
    key:
      secure: EiF8xTt3IKzYDbytjLMhlQwHlMqWQxWpAcfMOxyuIWuFdIf016Z2SUihm85Z/uFF1im77ZXP/aanPu44S+UJh/tYziDuQPP48QCtkpk/1BarGTk4zr+YEWJspUdd3+b2bCOcF1JZiXnAiq/2pX2OTC5pUqmgZ/7/mR2LKhSuddHZotYj2j8JqFbdipM6EoeLOeHPQHRYWrQmPDVhSSuoI5SEeiWVnsRVX0mcVRTzpAC4qD9Q8oNs5GQlHxA/juYuyWr+sK6OAZd694QtIU0M5utLI7VY36+rTvHj52vZjQ07mk2K1/lrve4+Si/E8JxhfftaHg2x770QdTn2Nrh3r4Pj6BDYuTS+DMmtuAgG+6E2sqBvKL7tP8jeeVGWyateEyHcStwkfakB4lXkYm5ZgHl1f5/ehBPUkzBuBTOT5z/0k3lp6a737OTAlEQiosRtGoduy71SJE02H9+X0VETSkshQlbX8C0Xg1TH+wMtv2ZvVpE9hNHfmmctjgSk2DyKmLvgff+hf9qg6uUn+WSLR5yv2iOk6HEEVJ7r+5TKqujjRMdWGGark/oQxepzlgQko4VPMKXr/Q0BhdYwdl6RswVTcLw/UGiiiNu91GryycJUIWwMGqfReN9QXVYAt0wUIw2CgPaOR90CtM3hwHkbYVXaKKqDvUsyrFHRANF/P3M=
    secret:
      secure: O9Sn1kfGANYeemELoQwWcvSAdsd+lNgKi64XSNnA7GcNU6Wb9VgY2e1TowaqIuvMnETm86kxyeDqFjkTv69CnsEBGl+wf9Yq2B3rhqqIv7SOmt2vF9O7+Yrc3mE3aLMs8z2ATX9D5pvstQDj55pHokHaQcBklgDbGV1acoDCQB9g016eMGqc4jEFpSBb9FxH+bGYX6rh3BK4oZ/MaTXEOmDEExovpmOw0xS9/P2QdGsevmyUelzpuIHKWDAY7xUNrMYfMovrccmA3NVz1GceL2pI6IQ6L3E7EPdZ0/NPwp5yO3k8TnS8nuYwq6+WJXVkbXnYvgzU7CI6BIMimd0yk2nAd2paKIKqYugh2jiW7WNMTt3qB9ZHrgPwuHbOQC9U6ca/LHaLFIo3bPF7FLuKJrdYSa2Lgpm02tSoJhbzUgNuHsZ46jZ/5kAR9xwai3CT/JlDl1ltoAk+u6k5vs2fKEJ1jhAIm0y9s7bvwVLRSwtzDuvH2GzA/6Hzj3UFJ0X5jrKF4lWyTLLX4wmTInmiY9pWkRi9+h6HpS3ZagC33Wme5UOVaVI0BD0sPVboKDmEEWTdYY1BjsGW7l1vEZg6jhBz3SGH6yrOHgng2qP4pCly2itSsrHwWBkcjo9YvV9PVuofXCJ79Q+7sYCElexTMdPN/9zE6SP4AaUp0B87t58=
