name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 13
    - run: mvn package
    - uses: actions/upload-artifact@v2-preview
      with:
        name: massim-2020
        path: target/massim-*.tar.gz
